#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:20:00

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=1
#SBATCH --mem=10G
#SBATCH --time=00:20:00

set -x
set -e

mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_report

singularity exec docker://brainlife/mne:1.2.1 python3 main.py
